// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_slice: dynamic(() => import("./LinksSlice")),
  rich_text: dynamic(() => import("./RichText")),
};
